language: php

os:
    - linux

php:
    - '7.1'
    - '7.2'

script:
    - composer install
    - composer dump-autoload
    - ./vendor/bin/phpunit tests --verbose --colors --process-isolation

branches:
    except:
        - gh-pages
