language: php

os:
    - linux
    - osx

php:
    - 7.1
    - 7.0
    - 7.2

before_script:
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --configuration phpunit.xml
